import React, { useState, useEffect } from 'react';
import {
    Box,
    Typography,
    Paper,
    Table,
    TableBody,
    TableCell,
    TableContainer,
    TableHead,
    TableRow,
    Button,
    Chip,
    Fade,
    CircularProgress,
    useTheme,
    alpha,
} from '@mui/material';
import {
    Description as ReportIcon,
    OpenInNew as OpenIcon,
} from '@mui/icons-material';

interface ReportRecord {
    id: string;
    form_id: string;
    generated_by: string;
    file_path: string;
    generated_at: string;
    form_name: string;
    generated_by_username: string;
}

const ReportsPage: React.FC = () => {
    const theme = useTheme();
    const [reports, setReports] = useState<ReportRecord[]>([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        (async () => {
            try {
                const result = await window.api.getReports();
                setReports(result);
            } catch {
                // ignore
            } finally {
                setLoading(false);
            }
        })();
    }, []);

    const handleOpenFile = async (filePath: string) => {
        await window.api.openFile(filePath);
    };

    /** Extract just the filename from a full path. */
    const getFileName = (filePath: string): string => {
        return filePath.split(/[\\/]/).pop() || 'report.docx';
    };

    return (
        <Fade in timeout={500}>
            <Box sx={{ maxWidth: 900, mx: 'auto' }}>
                {/* Header */}
                <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, mb: 3 }}>
                    <ReportIcon sx={{ fontSize: 28, color: theme.palette.primary.main }} />
                    <Typography variant="h5">Reports</Typography>
                </Box>

                {/* Reports Table */}
                <Paper elevation={0} sx={{ border: `1px solid ${theme.palette.divider}`, overflow: 'hidden' }}>
                    {loading ? (
                        <Box sx={{ p: 4, textAlign: 'center' }}>
                            <CircularProgress size={32} />
                        </Box>
                    ) : (
                        <TableContainer>
                            <Table>
                                <TableHead>
                                    <TableRow>
                                        <TableCell sx={{ fontWeight: 600 }}>Report</TableCell>
                                        <TableCell sx={{ fontWeight: 600 }}>Form</TableCell>
                                        <TableCell sx={{ fontWeight: 600 }}>Generated By</TableCell>
                                        <TableCell sx={{ fontWeight: 600 }}>Date</TableCell>
                                        <TableCell sx={{ fontWeight: 600 }} align="right">
                                            Actions
                                        </TableCell>
                                    </TableRow>
                                </TableHead>
                                <TableBody>
                                    {reports.map((report) => (
                                        <TableRow key={report.id} hover>
                                            <TableCell>
                                                <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                                                    <ReportIcon
                                                        sx={{ fontSize: 18, color: theme.palette.primary.main }}
                                                    />
                                                    <Typography
                                                        variant="body2"
                                                        sx={{ fontWeight: 500, fontSize: '0.82rem' }}
                                                    >
                                                        {getFileName(report.file_path)}
                                                    </Typography>
                                                </Box>
                                            </TableCell>
                                            <TableCell>
                                                <Chip
                                                    label={report.form_name}
                                                    size="small"
                                                    sx={{
                                                        fontSize: '0.72rem',
                                                        height: 22,
                                                        backgroundColor: alpha(theme.palette.info.main, 0.1),
                                                        color: theme.palette.info.main,
                                                    }}
                                                />
                                            </TableCell>
                                            <TableCell>
                                                <Typography variant="body2" sx={{ color: 'text.secondary' }}>
                                                    {report.generated_by_username}
                                                </Typography>
                                            </TableCell>
                                            <TableCell>
                                                <Typography variant="body2" sx={{ color: 'text.secondary' }}>
                                                    {new Date(report.generated_at).toLocaleString()}
                                                </Typography>
                                            </TableCell>
                                            <TableCell align="right">
                                                <Button
                                                    size="small"
                                                    startIcon={<OpenIcon />}
                                                    onClick={() => handleOpenFile(report.file_path)}
                                                    sx={{ textTransform: 'none' }}
                                                >
                                                    Open
                                                </Button>
                                            </TableCell>
                                        </TableRow>
                                    ))}
                                    {reports.length === 0 && (
                                        <TableRow>
                                            <TableCell colSpan={5} sx={{ textAlign: 'center', py: 6 }}>
                                                <ReportIcon sx={{ fontSize: 48, color: 'text.disabled', mb: 1 }} />
                                                <Typography
                                                    variant="body1"
                                                    sx={{ color: 'text.secondary' }}
                                                >
                                                    No reports yet
                                                </Typography>
                                                <Typography
                                                    variant="body2"
                                                    sx={{ color: 'text.disabled', mt: 0.5 }}
                                                >
                                                    Generate a report from the Generate Report page
                                                </Typography>
                                            </TableCell>
                                        </TableRow>
                                    )}
                                </TableBody>
                            </Table>
                        </TableContainer>
                    )}
                </Paper>
            </Box>
        </Fade>
    );
};

export default ReportsPage;
